packetery/readme.txt, packetery/src/Packetery/Module/Checkout.php, packetery/template/checkout/country-error.latte
=> PES-595: no country in checkout fix

src/Packetery/Module/Order/GridExtender.php, src/Packetery/Module/Plugin.php
The display of filter links has been limited to the order overview page.
=> PES-686: filter links limited to order grid

public/admin-grid-order-edit.js, src/Packetery/Core/Entity/Order.php, src/Packetery/Module/Order/BulkActions.php, src/Packetery/Module/Order/Controller.php, src/Packetery/Module/Order/GridExtender.php, src/Packetery/Module/Order/LabelPrint.php, src/Packetery/Module/Order/Metabox.php, src/Packetery/Module/Order/Repository.php, template/order/export-result.latte
* Fixed: Actions run on deleted order now give proper error messages
=> PES-651: treating deleted orders actions

src/Packetery/Module/Order/PacketSubmitter.php
Added packetAttributes if the packet was successfully sent.
=> PES-828: API Log - added packetAttributes

src/Packetery/Module/Order/PacketCanceller.php
=> PES-913: Fix logging on packet cancellation. 

public/checkout.js, readme.txt, src/Packetery/Module/Checkout.php
Adds support for Toret GoPay plugin in checkout
=> PES-981 Add shippingMethodId to ShippingRateId

languages/packeta.pot, src/Packetery/Module/Options/Page.php, src/Packetery/Module/Order/Modal.php, src/Packetery/Module/Order/PacketSynchronizer.php, src/Packetery/Module/Product/DataTab.php
fixed status translations, another translation string
=> PES-1060: fix translations

src/Packetery/Module/Order/PacketSynchronizer.php
=> PES-1060: status translations

README.md, config/config.neon, src/Packetery/Core/Api/Soap/Client.php, src/Packetery/Core/Api/Soap/CreatePacketMapper.php, src/Packetery/Core/Api/Soap/Request/CreatePacket.php, src/Packetery/Core/Api/Soap/RequestFactory/CreatePacketRequest.php, src/Packetery/Module/Order/PacketSubmitter.php
=> PES-1064_create_packet_filter

src/Packetery/Module/Order/PacketSubmitter.php
Zapomenuta radka z velkeho rebasu na dev.
=> PES-558 Rebase fix

public/checkout.js
Reverts Zasilkovna/WooCommerce#373
=> Revert "PES-1214: widget button is now displayed for e-shops without delivery…"

src/Packetery/Module/Checkout.php, src/Packetery/Module/Options/Page.php, src/Packetery/Module/Options/Provider.php, template/options/page-tabs/general.latte
Feature: Added a new setting option which enables a user to choose whether he wants to show the shipping is free(if eligible), or not.
=> PES-1717: WP: Možnost nastavit zda zobrazovat "zdarma" u přepravní metody v pokladně

src/Packetery/Module/EntityFactory/Carrier.php, template/carrier/carrier.latte
Amended the way we set the carrier in the Factory to allow certain carriers to be able to use the age verification feature, then removed the info message in the front-end and added it as a description under the age verification settings field.
=> PES-1750:  Age verification (HD Packeta)

config/config.neon, src/Packetery/Module/CustomsDeclaration/Repository.php, src/Packetery/Module/HookHandler.php, src/Packetery/Module/Order/MetaboxesWrapper.php, src/Packetery/Module/Order/Repository.php, src/Packetery/Module/Plugin.php
PES-1812: Added a new feature where we delete order entries with all its cascading data in the DB when changing the carrier from Packetery to something else.
=> Deleting order entries in the DB

src/Packetery/Module/HookHandler.php, src/Packetery/Module/Order/MetaboxesWrapper.php
Swapped the old hook we used for updating order details in the Metabox for a new one to fix the compatibility with the HPOS.
=> PES-1827:  Fixed Compatibility with HPOS

src/Packetery/Core/Entity/Carrier.php, src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/FormValidators.php, template/carrier/carrier.latte
Added 2 extra parameters in settings for carriers who participate in car deliveries.
=> PES-1866: Added 2 extra parameters in settings for carriers regarding Car Deliveries.

src/Packetery/Module/Carrier/OptionsPage.php
=> PES-1887: Removed unused parameter in the Car Delivery settings.

public/checkout.js, src/Packetery/Module/Api/Internal/CheckoutController.php, src/Packetery/Module/Api/Internal/CheckoutRouter.php, src/Packetery/Module/Carrier/EntityRepository.php, src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/Carrier/Repository.php, src/Packetery/Module/Checkout.php, src/Packetery/Module/Order/Attribute.php
An early stage implementation of Packeta Car Delivery.
=> PES-1833: Implemented a new carrier, Car Delivery.

src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/Checkout.php
Fixed the errors and added a default value for daysUntilDelivery in CD settings options.
=> PES-1918: Car delivery checkout errors

src/Packetery/Core/Api/Soap/CreatePacketMapper.php, src/Packetery/Core/Api/Soap/Request/CreatePacket.php, src/Packetery/Core/Entity/Order.php
Adjusted the code to be able to send data to the widget for car delivery.
=> PES-1906: Car Delivery data for Packeta widget

public/checkout.js
=> PES-1943: Fixed the issue with the address not being set properly.

public/checkout.js, src/Packetery/Module/Checkout.php, template/checkout/car-delivery-estimated-delivery-date.latte
Removed some unwanted code and added a new section under the widget for Packetery Car Delivery where we display an estimated delivery date when address is selected.
=> PES-1931: Removed displayed verified address and added estimated delivery date

src/Packetery/Module/Order/AttributeMapper.php
=> PES-1962: Removed false parameter.

config/config.local.neon.example, config/config.neon, src/Packetery/Module/NativeCarrierSettingsConfig.php
=> PES-1991: Added a new config for native packeta carrier settings.

config/config.local.neon.example, config/config.neon, src/Packetery/Module/Order/CarrierModal.php, src/Packetery/Module/WCNativeCarrierSettingsConfig.php
We show the carrier change button in the Packeta Metabox only if the native carrier settings is inactive.
=> PES-1992: Metabox Change Carrier Button

src/Packetery/Module/Options/FeatureFlagManager.php
=> PES-1544: Swapped guzzle client for native WP function to fetch flags.

config/config.local.neon.example, config/config.neon, public/admin.css, src/Packetery/Module/Carrier/CountryListingPage.php, src/Packetery/Module/Carrier/CountryListingTemplateParams.php, src/Packetery/Module/Options/FeatureFlagManager.php, template/carrier/carriersUpdater.latte, template/carrier/countries.latte, template/carrier/wcNativeSettings.latte
=> PES-1995: Created a new settings page for carriers.

src/Packetery/Core/Helper.php, src/Packetery/Module/Options/Page.php, template/options/page-tabs/general.latte
We can now set the default weight as a float with up to 3 decimals.
=> PES-2037: Default weight with 3 decimals in settings.

public/admin.css, src/Packetery/Core/Entity/Order.php, src/Packetery/Module/Checkout.php, src/Packetery/Module/Options/Page.php, src/Packetery/Module/Options/Provider.php, template/options/page-tabs/general.latte
Dimension are now being saved only if required by the carrier.
=> PES-1933:  Default consignment's dimensions settings

src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/Options/Page.php
=> PES-2044: Hotfix to sanitise the default_weight input.

public/admin.css, src/Packetery/Module/Carrier/CountryListingPage.php, src/Packetery/Module/Carrier/CountryListingTemplateParams.php, template/carrier/wcNativeSettings.latte
Added a new searchbox to be able to filter carriers in the carrier settings.
=> PES-1994: Filtering carriers

src/Packetery/Module/Options/Provider.php
Reverts Zasilkovna/WooCommerce#540
=> Revert "PES-2077: Undefined array key new carrier settings enabled"

public/admin.css, src/Packetery/Module/Carrier/CountryListingPage.php, src/Packetery/Module/Carrier/CountryListingTemplateParams.php, template/carrier/wcNativeSettings.latte
Reverts Zasilkovna/WooCommerce#537
=> Revert "PES-1994: Filtering carriers"

languages/packeta.pot, packeta.php, readme.txt, src/Packetery/Module/Plugin.php
Incremented the version of plugin. Generated new translations and added info to the readme file.
=> PES-2090: New release 1.7.3

template/order/metabox-common.latte
=> PES-2248: Added a condition to check if the url is set.

src/Packetery/Core/Api/Soap/Client.php, src/Packetery/Module/Carrier/CarDeliveryConfig.php, src/Packetery/Module/Carrier/CountryListingPage.php, src/Packetery/Module/Carrier/EntityRepository.php, src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/Checkout.php, src/Packetery/Module/Product/DataTab.php, src/Packetery/Module/ProductCategory/FormFields.php
Added extra logic to show/hide Car Delivery options in Product and Product Category.
=> PES-2252: Remove cardelivery when suppressed in product and category

changelog.txt, languages/packeta.pot, packeta.php, readme.txt, src/Packetery/Module/Plugin.php, src/Packetery/Module/Upgrade.php
=> PES-2267: Pre-requisites for a new release 1.8.0

src/Packetery/Module/Order/Repository.php
Restored deleted PickupPointsConfig dependency in Order Repository.
=> PES-2275: Missing dependency

.ecrc, .editorconfig, README.md, composer-deps.json, composer.json, composer.lock, config/config.local.neon.example, phpstan/composer.json, phpunit.xml.dist, public/css/custom-front.css, src/PacketaWidget/block.json, src/Packetery/Module/CustomsDeclaration/Repository.php, src/Packetery/Module/Order/Repository.php, src/Packetery/Module/Upgrade/Version_1_4_2.php, template/carrier/carrier.latte, template/dashboard-widget.latte, template/options/page-tabs/general.latte, template/order/customs-declaration-item.latte, template/order/customs-declaration-metabox.latte, template/order/delivery-detail.latte, template/order/detail.latte, template/order/grid-column-packetery.latte, template/order/label-print.latte, tests/Core/Api/Rest/PickupPointValidateTest.php
Added github pipeline to check files against to editorconfig file. 
review without whitespaces https://github.com/Zasilkovna/WooCommerce/pull/621/files?diff=unified&w=1
=> PES-2292: editor config pipeline

composer.json, composer.lock, phpcs.xml, src/Packetery/Module/Carrier/OptionsPage.php, src/Packetery/Module/Options/Page.php, src/Packetery/Module/Order/Modal.php
PES-2301: SlevomatCodingStandard.Namespaces.UnusedUses sniffer rule added, corresponding fixes
=> PES-2301: SlevomatCodingStandard.Namespaces.UnusedUses sniffer rule added, corresponding fixes

src/Packetery/Module/Options/Page.php
Reverts Zasilkovna/WooCommerce#626
=> Revert "PES-2327: fixed validation for hidden default dimensions inputs with …"

changelog.txt, languages/packeta.pot, packeta.php, readme.txt, src/Packetery/Module/Plugin.php, src/Packetery/Module/Upgrade.php
Upgraded plugin version for a new release.
=> PES-2353: Release 1.8.3

src/Packetery/Module/Options/FlagManager/FeatureFlagProvider.php, tests/Module/Options/FlagManager/FeatureFlagProviderTest.php
Temporarily enabled split until it gets completely removed in the phase 2.
=> PES-2352:  Removing Split - Phase 1

config/config.local.neon.example, config/config.neon, src/Packetery/Core/Api/Soap/Client.php
Moved the WSDL URL to the config file and applied the changes within the code.
=> PES-2342: Moved WSDL url to the config file

src/Packetery/Core/CoreHelper.php, tests/Core/HelperTest.php
Fixed the static function where it would falsely trim a submitted full number ending with 0.
=> PES-2358: Default weight plugin settings

config/config.neon, src/Packetery/Core/CoreHelper.php, src/Packetery/Module/Api/Internal/OrderController.php, src/Packetery/Module/Checkout.php, src/Packetery/Module/EntityFactory/SizeFactory.php, src/Packetery/Module/FormFactory.php, src/Packetery/Module/ModuleHelper.php, src/Packetery/Module/Options/OptionsProvider.php, src/Packetery/Module/Options/Page.php, src/Packetery/Module/Order/Form.php, src/Packetery/Module/Order/GridExtender.php, src/Packetery/Module/Order/Metabox.php, template/options/page-tabs/general.latte, template/order/grid-column-packetery.latte, tests/Module/CheckoutTest.php, tests/Module/EntityFactory/SizeFactoryTest.php, tests/Module/ModuleHelperTest.php, tests/Module/Options/OptionsProviderTest.php, tests/bootstrap.php
=> PES-2408: New default dimensions settings

.ecrc, .github/workflows/run-phpunit.yml, composer.json, composer.lock, phpunit.xml.dist, tests/Module/Order/PacketSynchronizerTest.php
Run Action => Coverage => import `clover.xml`
=> PES-2398 code coverage

bootstrap.php, config/config.neon, packeta.php, src/Packetery/Module/FormFactory.php, src/Packetery/Module/Framework/TranslationTrait.php, src/Packetery/Module/Hooks/PluginHooks.php, src/Packetery/Module/HttpRequestFactory.php, src/Packetery/Module/ModuleHelper.php
Added a new HttpRequestFactory class to manage HTTP request creation with enhanced flexibility for different runtime contexts, such as CLI and web requests. Updated related components to utilize the new factory, removed the global cookie transformation logic, and refined translation domain management for better modularity. These changes improve maintainability and prepare the codebase for future enhancements.
=> PES-2678 Introduce HttpRequestFactory and refactor request handling

.github/workflows/composer-normalize.yml, composer.json, composer.lock
https://github.com/ergebnis/composer-normalize
=> PES-2916: composer normalize
